inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Style/SymbolArray:
  Enabled: false
  